'use client'

import React from 'react'
import { motion } from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { cn } from '@/lib/utils'
import { Report } from '@/types/report'
import { GlassCard, Button } from '@/components/ui'
import { formatDate } from '@/lib/utils'
import {
    XMarkIcon,
    ArrowDownTrayIcon,
    ClipboardDocumentIcon,
    PrinterIcon
} from '@heroicons/react/24/outline'

interface ReportViewerProps {
    report: Report
    onClose: () => void
    className?: string
}

export function ReportViewer({ report, onClose, className }: ReportViewerProps) {
    const handleCopy = () => {
        navigator.clipboard.writeText(report.content)
        // Could add toast notification here
    }

    const handleDownload = () => {
        const blob = new Blob([report.content], { type: 'text/markdown' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${report.title.replace(/\s+/g, '_')}.md`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
    }

    const handlePrint = () => {
        window.print()
    }

    return (
        <motion.div
            className={cn('flex flex-col h-full', className)}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
        >
            {/* Header */}
            <div className="flex items-start justify-between gap-4 p-6 border-b border-white/[0.08]">
                <div className="flex-1 min-w-0">
                    <motion.h1
                        className="text-2xl font-bold text-white mb-2"
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                    >
                        {report.title}
                    </motion.h1>
                    <div className="flex flex-wrap items-center gap-3 text-sm text-muted">
                        <span className="text-neon-cyan font-medium">{report.company}</span>
                        <span>•</span>
                        <span>{formatDate(report.createdAt)}</span>
                        {report.metadata?.wordCount && (
                            <>
                                <span>•</span>
                                <span>{report.metadata.wordCount.toLocaleString()} words</span>
                            </>
                        )}
                    </div>
                </div>

                {/* Actions */}
                <div className="flex items-center gap-2">
                    <Button
                        variant="ghost"
                        size="sm"
                        onClick={handleCopy}
                        leftIcon={<ClipboardDocumentIcon className="w-4 h-4" />}
                    >
                        Copy
                    </Button>
                    <Button
                        variant="ghost"
                        size="sm"
                        onClick={handleDownload}
                        leftIcon={<ArrowDownTrayIcon className="w-4 h-4" />}
                    >
                        Download
                    </Button>
                    <Button
                        variant="ghost"
                        size="sm"
                        onClick={handlePrint}
                        leftIcon={<PrinterIcon className="w-4 h-4" />}
                        className="hidden md:flex"
                    >
                        Print
                    </Button>
                    <button
                        onClick={onClose}
                        className="p-2 rounded-lg hover:bg-white/10 text-muted hover:text-white transition-all ml-2"
                    >
                        <XMarkIcon className="w-5 h-5" />
                    </button>
                </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6">
                <GlassCard className="max-w-4xl mx-auto" padding="lg">
                    <div className="markdown-content prose prose-invert max-w-none">
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                            {report.content}
                        </ReactMarkdown>
                    </div>
                </GlassCard>
            </div>

            {/* Agents used */}
            {report.agents && report.agents.length > 0 && (
                <div className="p-4 border-t border-white/[0.08] bg-space-50/50">
                    <div className="flex items-center gap-2 text-sm text-muted">
                        <span>Generated by:</span>
                        <div className="flex gap-2">
                            {report.agents.map((agent) => (
                                <span
                                    key={agent}
                                    className="px-2 py-1 rounded-full bg-white/5 text-xs capitalize"
                                >
                                    {agent}
                                </span>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </motion.div>
    )
}
